version: '3.8'

services:
  redis:
    image: "redis"
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
