[tool.poetry]
name = "alecodereviewai"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.10.1"
pydantic-settings = "^2.6.1"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
black = "^24.10.0"
aiohttp = "^3.11.7"
langchain = "^0.3.8"
langchain-openai = "^0.2.9"
langchain-community = "^0.3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
